name: Deploy to Railway Dev Env

on:
  push:
    brances: [develop]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        users: actions/checkout@v2
        with:
          node-version: 16.x
      
      - name: Install packages
        run: npm install

      - name: Install Railway
        run: npm i -g @railway/cli

      - name: Deploy
        run: railway up
        env: 
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_DEV_TOKEN }}